name = "kavomant"
compatibility_date = "2025-08-18"

[site]
bucket = "./out"

[pages_build_output_dir]
directory = "./out"

[env.production]
name = "kavomant"

[env.staging]
name = "kavomant-staging"
